Cargo.toml, benches/read_entry.rs, benches/read_metadata.rs, examples/write_dir.rs, examples/write_sample.rs, fuzz/fuzz_targets/fuzz_write.rs, src/read.rs, src/types.rs, src/unstable.rs, src/write.rs, tests/end_to_end.rs, tests/zip_crypto.rs
When `extra_data` and `central_extra_data` were added to FileOptions we lost the ability to implement Copy for FileOptions. 
Plenty of people will want to Zip a basic set of files. But now we have an unnecessary Atomic value being incremented and decremented. Also an empty allocation inside the Vec
So this solution has FileOptions take a Generic Parameter to hold "Extra Options" This can be the Unit type or ExtendedFileOptions
This also puts extra_data and central_extra_data in an Option inside ZipFileData removing the Atomic usage in some cases there too. 
This does break the current code as people will need to specify the generic parameter or change FileOptions to either SimpleFileOptions or  FullFileOptions
I also corrected the write_dir test to remove the deprecated API calls
=> Allow copying File Options Again

.github/workflows/ci.yaml, .github/workflows/dependabot_automation.yml
This change allows me to submit future changes as PRs that will be auto-approved, rather than as direct pushes to master that would require other open PRs to be rebased.
=> Automatically approve my own PRs

README.md
=> doc: fix repo link in readme

CHANGELOG.md, Cargo.toml
* `zip`: 1.1.2 -> 1.1.3 (✓ API compatible changes)
<blockquote>
- Rare bug where find_and_parse would give up prematurely on detecting a false end-of-CDR header
</blockquote>
</p></details>
---
=> chore: release v1.1.3

Cargo.toml
This replaces https://github.com/zip-rs/zip-old/pull/429.
=> feat: Switch to pure-Rust versions of bzip and zstd in order to pass static compiles

Cargo.toml, benches/merge_archive.rs, src/read.rs, src/write.rs
See https://github.com/zip-rs/zip-old/pull/401. Closes #61.
=>  feat: add ZipWriter::merge_archive() to efficiently copy all entries from a ZipArchive

src/read.rs, src/write.rs
See https://github.com/zip-rs/zip-old/pull/400. Closes #57.
=>  feat: add ZipWriter::finish_into_readable()

.github/workflows/ci.yaml, benches/merge_archive.rs
This should detect issues in feature-gated parts of the code and their docstrings more reliably.
=> ci: Run cargo doc and clippy with default features, all features and no features

CHANGELOG.md, Cargo.toml
* `zip`: 1.1.3 -> 1.1.4 (✓ API compatible changes)
<blockquote>
- Build was failing with bzip2 enabled
- use is_dir in more places where Windows paths might be handled incorrectly
- Quick filter for paths that contain "/../" or "/./" or start with "./" or "../"
- Fast handling for separator-free paths
- Speed up logic if main separator isn't '/'
- Drop `normalized_components` slightly sooner when not using it
- Speed up `path_to_string` in cases where the path is already in the proper format
- Refactor: can short-circuit handling of paths that start with MAIN_SEPARATOR, no matter what MAIN_SEPARATOR is
- Bug fix: non-canonical path detection when MAIN_SEPARATOR is not slash or occurs twice in a row
- Bug fix: must recreate if . or .. …
=> chore: release v1.1.4

benches/merge_archive.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_write.rs, src/write.rs, tests/zip_crypto.rs
This prevents the reuse of a closed ZipWriter at compile-time; currently it's a runtime Err result.
=> refactor: Make `ZipWriter::finish()` consume the `ZipWriter`

CHANGELOG.md, Cargo.toml
* `zip`: 1.1.4 -> 1.2.0 (✓ API compatible changes)
<blockquote>
- Add method `decompressed_size()` so non-recursive ZIP bombs can be detected
- Make `ZipWriter::finish()` consume the `ZipWriter`
- Use panic! rather than abort to ensure the fuzz harness can process the failure
- Update fuzz_write to use replace_with
- Remove a drop that can no longer be explicit
- Add `#![allow(unexpected_cfgs)]` in nightly
</blockquote>
</p></details>
---
=> chore: release v1.2.0

CHANGELOG.md, Cargo.toml
* `zip`: 1.2.0 -> 1.2.1 (✓ API compatible changes)
<blockquote>
- Prevent panic when trying to read a file with an unsupported compression method
- Prevent panic after reading an invalid LZMA file
- Make `Stored` the default compression method if `Deflated` isn't available, so that zip files are readable by as much software as possible
- version_needed was wrong when e.g. cfg(bzip2) but current file wasn't bzip2 ([#100](https://github.com/zip-rs/zip2/pull/100))
- file paths shouldn't start with slashes ([#102](https://github.com/zip-rs/zip2/pull/102))
- Overhaul `impl Arbitrary for FileOptions`
- Remove unused `atomic` module
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release v1.2.1

CHANGELOG.md, Cargo.toml
* `zip`: 1.2.1 -> 1.2.2 (✓ API compatible changes)
<blockquote>
- Failed to clear "writing_raw" before finishing a symlink, leading to dropped extra fields
- Use boxed slice for archive comment, since it can't be concatenated
- Optimize for the fact that false signatures can't overlap with real ones
</blockquote>
</p></details>
---
=> chore: release v1.2.2

CHANGELOG.md, Cargo.toml
* `zip`: 1.2.2 -> 1.2.3 (✓ API compatible changes)
<blockquote>
- Remove a window when an extracted directory might be unexpectedly listable and/or `cd`able by non-owners
- Extract directory contents on Unix even if the directory doesn't have write permission (https://github.com/zip-rs/zip-old/issues/423)
- More conditionally-unused imports
</blockquote>
</p></details>
---
=> chore: release v1.2.3

CHANGELOG.md, Cargo.toml
* `zip`: 1.2.3 -> 1.3.0 (✓ API compatible changes)
<blockquote>
- Add `is_symlink` method
- Extract symlinks into symlinks on Unix and Windows, and fix a bug that affected making directories writable on MacOS
- Eliminate deprecation warning when `--all-features` implicitly enables the deprecated feature
- Check if archive contains a symlink's target, without borrowing both at the same time
- Eliminate a clone that's no longer necessary
- is_dir only needs to look at the filename
- Remove unnecessary #[cfg] attributes
- Fix borrow-of-moved-value
- Box<str> doesn't directly convert to PathBuf, so convert back to String first
- partial revert - only &str has chars(), but Box<str> should auto-deref
- contains_key needs a `Box<str>`, so …
=> chore: release v1.3.0

Cargo.toml, src/lib.rs
Currently, the  documentation cannot be built when the `deflate-zopfli` feature is enabled (see <https://github.com/zopfli-rs/zopfli/issues/42>). So I think when this issue is resolved it will be possible to build the  documentation with `all-features = true`.
To reproduce locally:
```sh
env RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc -F "aes-crypto bzip2 chrono deflate deflate64 deflate-zlib-ng lzma time zstd" --no-default-features
```
Screenshots:
=> docs: Enable `doc_auto_cfg` feature with Docs.rs

.github/workflows/ci.yaml, Cargo.toml, README.md
zopfli-rs/zopfli#42 was resolved in `zopfli` v0.8.1, so I enabled all features for Docs.rs. I also changed the MSV to v1.73.0, because the MSRV of `zopfli` v0.8.1 is v1.73.0. This is older than the latest 4 minor Rust versions,[^1] so this MSRV change seems fine.
[^1]: <https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html>
=> doc: Enable all features for Docs.rs

CHANGELOG.md, Cargo.toml
* `zip`: 1.3.0 -> 1.3.1 (✓ API compatible changes)
<blockquote>
- Make `deflate` enable both default implementations
- Merge the hidden deflate-flate2 flag into the public one
- Rename _deflate-non-zopfli to _deflate-flate2
- Reject encrypted and using_data_descriptor files slightly faster in read_zipfile_from_stream
- Convert `impl TryInto<NaiveDateTime> for DateTime` to `impl TryFrom<DateTime> for NaiveDateTime` ([#136](https://github.com/zip-rs/zip2/pull/136))
- Change default compression implementation to `flate2/zlib-ng`
- chore([#132](https://github.com/zip-rs/zip2/pull/132)): Attribution for some copied test data
- chore([#133](https://github.com/zip-rs/zip2/pull/133)): chmod -x src/result.rs
</blockquote>
</p></details>
--- …
=> chore: release v1.3.1

fuzz/fuzz_targets/fuzz_write.rs
`master` is broken, seemingly by a change in the `cargo` action: https://github.com/zip-rs/zip2/actions/runs/9185032790/job/25258374442
```rust
/home/runner/.cargo/bin/cargo fuzz cmin --all-features fuzz_write fuzz/corpus/fuzz_write -- fuzz/corpus/new_seed
Compiling zip-fuzz v0.0.0 (/home/runner/work/zip2/zip2/fuzz)
error: this method call resolves to `<&Box<[T]> as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<Box<[T]> as IntoIterator>::into_iter` in Rust 2024
Error:    --> fuzz_targets/fuzz_write.rs:134:52
|
134 |     for (operation, abort) in test_case.operations.into_iter() {
|                                                    ^^^^^^^^^
|
= warning: this changes meaning in Rust 2024
= note: `-D boxed-slice-into-iter` implied by `-D warnings`
= …
```
=> fix rust 2024 breakage with cargo v1 action

src/types.rs
Add the `since` field to the `deprecated` attribute for `DateTime::from_time` and `DateTime::to_time`.
- <https://docs.rs/zip/0.6.3/zip/struct.DateTime.html#method.from_time>
- <https://docs.rs/zip/0.6.4/zip/struct.DateTime.html#method.from_time>
=> chore: Add `since` to `deprecated`

src/types.rs
Since `time::OffsetDateTime` and `chrono::NaiveDateTime` implement these traits, so I implement them to `DateTime` as well.
=> Implement `PartialEq`, `Eq`, `PartialOrd`, `Ord`, `Hash` and `Display` for `DateTime`

src/aes.rs, src/read.rs, src/result.rs
This PR adds helper functions to enable users to access AES information for encrypted files.
context: I need this for https://github.com/agourlay/zip-password-finder where I used to have a fork of the previous zip repository just for those. Now seems like a good time to get off my fork :)
=> feat: Expose AES information

CHANGELOG.md, Cargo.toml
* `zip`: 1.3.1 -> 2.0.0
<blockquote>
- Add `fmt::Display` for `DateTime`
- Implement more traits for `DateTime`
- Change type of `last_modified_time` to `Option<DateTime>`
- [**breaking**] Rename `from_msdos` to `from_msdos_unchecked`, make it unsafe, and add `try_from_msdos` ([#145](https://github.com/zip-rs/zip2/pull/145))
- Continue to accept archives with invalid DateTime, and use `now_utc()` as default only when writing, not reading
</blockquote>
</p></details>
---
=> chore: release v2.0.0

src/types.rs
Add `TryFrom<(u16, u16)> for DateTime` and `From<DateTime> for (u16, u16)`. I think tuple (`(u16, u16)`) is better than array (`[u16; 2]`) to represent the MS-DOS date and time pair.
Closes #145
=> feat: Support mutual conversion between `DateTime` and MS-DOS pair

CHANGELOG.md, Cargo.toml
* `zip`: 2.0.0 -> 2.1.0
<blockquote>
- Support mutual conversion between `DateTime` and MS-DOS pair
- version-needed-to-extract was incorrect in central header, and version-made-by could be lower than that ([#100](https://github.com/zip-rs/zip2/pull/100))
- version-needed-to-extract was incorrect in central header, and version-made-by could be lower than that ([#100](https://github.com/zip-rs/zip2/pull/100))
- Another tweak to ensure `version_needed` is applied
- Tweaks to make `version_needed` and `version_made_by` work with recently-merged changes
</blockquote>
</p></details>
---
=> chore: release v2.1.0

CHANGELOG.md, Cargo.toml
* `zip`: 2.1.0 -> 2.1.1
<blockquote>
- Derive `Debug` for `ZipWriter`
- lower default version to 4.5 and use the version-needed-to-extract where feasible.
- use a MIN_VERSION constant
- Bug fixes for debug implementation
- Bug fixes for debug implementation
- Update unit tests
- Remove unused import
</blockquote>
</p></details>
---
=> chore: release v2.1.1

src/types.rs
- Change `DateTime` to not accept after 58 seconds. This is because the valid range of values for the seconds of the MS-DOS date and time is 0 to 58.
- Change `DateTime` to not accept invalid days (e.g., 2018-06-31 or 2018-02-29). Accepts leap days like 2024-02-29.
I couldn't find the specification about the valid range of the date and time of the ZIP format. However, since exFAT also uses the MS-DOS date and time for the date and time, I think the valid range of values is the same as this.
[7.4.8.1 DoubleSeconds Field](https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#7481-doubleseconds-field):
> The DoubleSeconds field shall describe the seconds portion of the Timestamp field, in two-second multiples.
>
> The valid range of values for this field shall be:
>
> - …
=> fix: Change `DateTime` to fully validate dates and discard inserted leap seconds

src/read.rs, src/read/config.rs, src/write.rs
Aside from supporting the current behavior which allows archives to be preceded by arbitrary data (added in fc749a09), this also allows detection of the offset to use by checking whether a central directory header is at the expected location. This is configurable because if the behavior were based only on detection, there could be false positives if archive data happened to contain a central directory header at the right spot.
The motivation for this was to support slightly non-standard central directory locations (such as described [here](https://taras.glek.net/post/optimized-zip-format/)).
=> feat: Allow the archive offset behavior of the reader to be configured.

CHANGELOG.md, Cargo.toml
* `zip`: 2.1.2 -> 2.1.3
<blockquote>
- Some date/time filters were previously unreliable (i.e. later-pass filters had no earliest-pass or latest-fail, and vice-versa)
- Decode Zip-Info UTF8 name and comment fields ([#159](https://github.com/zip-rs/zip2/pull/159))
- Return extended timestamp fields copied rather than borrowed ([#183](https://github.com/zip-rs/zip2/pull/183))
- Fix a new Clippy warning
- Fix a bug and inline `deserialize` for safety
- Add check for wrong-length blocks, and incorporate fixed-size requirement into the trait name
- Fix a fuzz failure by using checked_sub
- Add feature gate for new unit test
</blockquote>
</p></details>
---
=> chore: release v2.1.3

src/read/stream.rs
#79 is [failing CI](https://github.com/zip-rs/zip2/actions/runs/9702444803/job/26778309608?pr=79) due to a warning introduced in `src/read/stream.rs`:
```rust
error: struct `CounterVisitor` is never constructed
Error:    --> src/read/stream.rs:224:12
|
224 |     struct CounterVisitor(u64, u64);
|            ^^^^^^^^^^^^^^
|
= note: `CounterVisitor` has a derived impl for the trait `Default`, but this is intentionally ignored during dead code analysis
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
```
This appears to have been introduced by a newer nightly version updating behind our back and introducing this error, and not by any recent code change. I believe this should fix it.
We may be able to delete `CounterVisitor` …
=> fix dead code analysis warning

src/crc32.rs, src/read.rs
This replaces https://github.com/zip-rs/zip-old/pull/441.
=> fix: Improve several `Read` methods on `ZipFile`

src/read.rs, src/spec.rs, src/types.rs
- Remove allocations
- Make unsafe code easier to check
- Prevent potential `repr(Rust)` fields reordering
=> refactor: Improve `FixedSizeBlock`

.github/workflows/ci.yaml
=> ci(fuzz): Run fuzz_write_with_no_features only 40m times

src/lib.rs, src/spec.rs
See https://github.com/zip-rs/zip-old/pull/402. Closes #60.
=> feat: publicly export and document the zip64 threshold constants

src/compression.rs, src/read.rs, src/read/lzma.rs, src/read/xz.rs, src/write.rs
Multiples refactors to improve `read.rs`. 
- Split a `Decompressor` type (that we could even possibly make public)
- Remove dynamic state of `ZipFile` and its `crypto_reader` field
- Simplify `make_crypto_reader` parameters
Each commit can be reviewed separately.
=> Multiple refactors

CHANGELOG.md, Cargo.toml
* `zip`: 2.1.4 -> 2.1.5
<blockquote>
- change invalid_state() return type to io::Result<T>
</blockquote>
</p></details>
---
=> chore: release v2.1.5

fuzz/fuzz_targets/fuzz_write.rs, src/types.rs, src/write.rs
This will make it possible to copy and paste the output of `cargo fuzz fmt fuzz_write` into a unit test with only the following changes:
* Add the test function declaration and the final return of `Ok(())`.
* Remove `zopfli_buffer_size` and add `..Default::default()` to `FullFileOptions` instances, unless the test case depends on Zopfli.
* Add all the feature flags the test case depends on.
* Add `use` statements (with function scope if they're gated on feature flags).
* Run `cargo fmt --all`.
=> test(fuzz): Make `cargo fuzz fmt fuzz_write` output more reliably equivalent to the code path it follows

src/read.rs, src/write.rs
=> refactor: Eliminate some magic numbers and unnecessary path prefixes

fuzz/fuzz_targets/fuzz_write.rs
`fuzz_write` is likely to be faster when it consumes most of its contents and copying happens at the Arbitrary byte-string level.
=> test(fuzz): Consume self, and add initial junk

CHANGELOG.md, Cargo.toml
* `zip`: 2.1.5 -> 2.1.6
<blockquote>
- ([#33](https://github.com/zip-rs/zip2/pull/33)) Rare combination of settings could lead to writing a corrupt archive with overlength extra data, and data_start locations when reading the archive back were also wrong ([#221](https://github.com/zip-rs/zip2/pull/221))
- Eliminate some magic numbers and unnecessary path prefixes ([#225](https://github.com/zip-rs/zip2/pull/225))
</blockquote>
</p></details>
---
=> chore: release v2.1.6

src/read.rs
Introduces `ZipArchive::central_directory_start` to get the starting offset of the central directory (similar to `ZipFile::central_header_start`).
Closes #209
=> feat: Expose `ZipArchive::central_directory_start`

CHANGELOG.md, Cargo.toml
* `zip`: 2.1.6 -> 2.2.0
<blockquote>
- Expose `ZipArchive::central_directory_start` ([#232](https://github.com/zip-rs/zip2/pull/232))
</blockquote>
</p></details>
---
=> chore: release v2.2.0

src/read/stream.rs, src/spec.rs, src/types.rs, src/write.rs
This PR resolves a new batch of clippy warnings on nightly to unblock #247.
=> fix: resolve new clippy warnings on nightly

CHANGELOG.md, Cargo.toml
* `zip`: 2.2.0 -> 2.2.1 (✓ API compatible changes)
<blockquote>
- remove executable bit ([#238](https://github.com/zip-rs/zip2/pull/238))
- *(lzma)* fixed panic in case of invalid lzma stream ([#259](https://github.com/zip-rs/zip2/pull/259))
- resolve new clippy warnings on nightly ([#262](https://github.com/zip-rs/zip2/pull/262))
- resolve clippy warning in nightly ([#252](https://github.com/zip-rs/zip2/pull/252))
- Faster cde rejection ([#255](https://github.com/zip-rs/zip2/pull/255))
</blockquote>
</p></details>
---
=> chore: release v2.2.1

.github/workflows/ci.yaml, Cargo.toml
Hi,
I'm considering using zip2 in a project that has a downstream pin to `aes =0.8.3` but zip2 requires `aes ^0.8.4`.
It seems like your current strategy is to periodically bump dependency versions to the latest versions, even for SemVer-compatible releases. Is this a measure to ensure that security-critical bugfixes are always picked up when using recent versions of zip2? If not: Would you be fine with more relaxed version bounds for zip2's dependencies?
In this PR I've added a CI job that tests the project with the lowest-compatible dependency versions (`cargo update -Zminimal-versions`), bumped an outdated dev-dependency that breaks builds with minimal versions, and relaxed versions of the project's dependencies where appropriate.
Feel free to merge or close :upside_down_face: 
Thanks!
=> deps: Relax dependency versions

CHANGELOG.md, Cargo.toml
* `zip`: 2.2.1 -> 2.2.2 (✓ API compatible changes)
<blockquote>
- rewrite the EOCD/EOCD64 detection to fix extreme performance regression (#247)
</blockquote>
</p></details>
---
=> chore: release v2.2.2

CHANGELOG.md, Cargo.toml
* `zip`: 2.2.2 -> 2.2.3 (✓ API compatible changes)
<blockquote>
- Change the inner structure of `DateTime` (#267)
- cargo fix --edition
</blockquote>
</p></details>
---
=> chore: release v2.2.3

.github/workflows/ci.yaml, fuzz_write/src/main.rs
This PR adds steps to run `cargo fmt` and `cargo clippy` to `fuzz_write` and `fuzz_read`, also fixed some issues found by `fmt` and `clippy`.
=> style: lint fuzz projects in CI

src/path.rs, src/read.rs, src/read/stream.rs, src/write.rs
=> chore: Fix clippy and cargo fmt warnings

src/read.rs
Fix to https://github.com/zip-rs/zip2/issues/312#issue-2923921427
- Added `File` to use statement. 
Found additional error (E0599) at line 463.
- Added `?` operator after `output`. (`use the ? operator to extract `File` value, propagating a `Result::Err` value to caller`)
Replicated user's original test. Tested with Rust 1.85.0 on Windows 10 22H2 19045.5608. `cargo check --target wasm32-unknown-unknown --no-default-features`.
Besides some clippy messages, no other errors show up.
=> fix: wasm build failure due to a missing use statement 

CHANGELOG.md, Cargo.toml
* `zip`: 2.3.0 -> 2.4.0 (✓ API compatible changes)
<blockquote>
- `ZipArchive::root_dir` and `ZipArchive::extract_unwrapped_root_dir` ([#304](https://github.com/zip-rs/zip2/pull/304))
- wasm build failure due to a missing use statement  ([#313](https://github.com/zip-rs/zip2/pull/313))
</blockquote>
</p></details>
---
=> chore: release v2.4.0

CHANGELOG.md, Cargo.toml
* `zip`: 2.4.1 -> 2.4.2 (✓ API compatible changes)
<blockquote>
- `deep_copy_file` produced a mangled file header on big-endian platforms
</blockquote>
</p></details>
---
=> chore: release v2.4.2

fuzz_write/src/main.rs, src/extra_fields/zipinfo_utf8.rs, src/read.rs, src/read/stream.rs, src/result.rs, src/spec.rs, src/types.rs, src/write.rs
This RP include duplicated filename in returned `ZipResult`. Also introduce a macro `invalid!` to help construct `ZipError::InvalidArchive`.
Close #127
=> fix: improve error message for duplicated file

Cargo.toml, src/result.rs
- Improve docs by removing `{0}` from them
- Follow std recommendation for errors (lowercase)
- Remove `thiserror` and `displaydoc` dependencies as they are easily manually implemented as the error enum is pretty small
=> deps: remove thiserror and displaydoc dependencies

CHANGELOG.md, Cargo.toml
* `zip`: 2.4.2 -> 2.5.0 (✓ API compatible changes)
<blockquote>
- Add support for `time::PrimitiveDateTime` ([#322](https://github.com/zip-rs/zip2/pull/322))
- Add `jiff` integration ([#323](https://github.com/zip-rs/zip2/pull/323))
- improve error message for duplicated file ([#277](https://github.com/zip-rs/zip2/pull/277))
</blockquote>
</p></details>
---
=> chore: release v2.5.0

src/read.rs
fix: handling reading password protected files with msdos date of 0
Multiple zip utilities create password protected zip files that use the msdos
date of zero.  This PR allows said zip files to be opened with this crate.
fixes #282
=> fix: handling decryption with msdos date of 0

CHANGELOG.md, Cargo.toml
* `zip`: 2.6.0 -> 2.6.1 (✓ API compatible changes)
<blockquote>
- avoid scanning through all local file headers while opening an archive ([#281](https://github.com/zip-rs/zip2/pull/281))
</blockquote>
</p></details>
---
=> chore: release v2.6.1

.github/workflows/ci.yaml, Cargo.toml, src/compression.rs, src/read.rs, src/write.rs, tests/end_to_end.rs, tests/extract_symlink.rs, tests/repro_old423.rs, tests/root_dir.rs, tests/zip_crypto.rs
Fixes #347.
Zopfli is a **compression only** algorithm. This means that it cannot be used to **decompress** DEFLATE streams. However, the code currently implies this, and tries to build flate2-related code paths because zopfli sets `_deflate_any`.
However, unsetting `_deflate_any` is not enough: zopfli can still compress DEFLATE streams even if it can't decompress them.
So to make sure everything is still OK, allow decompression of DEFLATE only when `flate2` is active, but allow compression both when only `zopfli` is active (in this case, shift the compression level by 9 so the same functionality takes place as when flate2 is enabled), and when both `zopfli` and `flate2` are active (in this case, use `flate2` when compression level is less than 9, and `zopfli` when compression level is …
=> fix: When only zopfli is available, decompression of deflate should not be possible

Cargo.toml, README.md, src/build.rs
=> chore!: Drop deprecated `deflate-miniz` feature flag

.github/workflows/ci.yaml, Cargo.toml, README.md, examples/write_dir.rs
Move `deflate-zlib` to `deflate-flate2-zlib` to make it clear it's a
flate2 backend, and add `deflate-flate2-zlib-rs` to use the zlib-rs
backend. Make the latter the default.
Bump the required flate2 version to one that works with zlib-rs 0.5.0,
which removes all compatibility considerations by no longer exporting
any C symbols that would conflict with another zlib.
Remove `deflate-zlib-ng`, largely superseded by
`deflate-flate2-zlib-rs`.
Remove no-op backend-specific code from an example.
Add documentation for the flate2-related feature flags.
=> feat!: zip 3.0: Adjust flate2-related features for 3.0

CHANGELOG.md, Cargo.toml
* `zip`: 2.6.1 -> 3.0.0 (⚠ API breaking changes)
```text
--- failure feature_missing: package feature removed or renamed ---
Description:
A feature has been removed from this package's Cargo.toml. This will break downstream crates which enable that feature.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/feature_missing.ron
Failed in:
feature flate2 in the package's Cargo.toml
feature deflate-zlib-ng in the package's Cargo.toml
feature deflate-miniz in the package's Cargo.toml
feature proc-macro2 in the package's Cargo.toml
feature deflate-zlib in the package's Cargo.toml
```
<blockquote>
- return correct offset in …
=> chore: release v3.0.0

src/read.rs
As described by #251 , there is currently a check in `read.rs` that invalidates Zip64 archives where the field "Version needed to extract" contained in the EOCD64 header is higher than the field "Version made by", making `ZipArchive::new()` return `InvalidArchive("Could not find EOCD")` for these types of files.
Although the current behavior may be considered correct, there is currently no other tool as far as I am aware that returns an error or fails to parse these files completely. `zip -T` and `unzip -t`, for example, validate these types of archives with no errors.
This issue is somewhat prevalent as it disallows reading Zip64 archives downloaded from GitHub directly.
Even if this pull request is not accepted, I would still suggest improving the currently returning error message, as …
=> fix: Allow extraction of Zip64 archives where EOCD64's field "Version needed to extract" is higher than "Version made by"

CHANGELOG.md, Cargo.toml
* `zip`: 3.0.0 -> 4.0.0 (⚠ API breaking changes)
```text
--- failure feature_missing: package feature removed or renamed ---
Description:
A feature has been removed from this package's Cargo.toml. This will break downstream crates which enable that feature.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.41.0/src/lints/feature_missing.ron
Failed in:
feature aes in the package's Cargo.toml
feature constant_time_eq in the package's Cargo.toml
feature zopfli in the package's Cargo.toml
feature lzma-rs in the package's Cargo.toml
```
<blockquote>
- Allow extraction of Zip64 where "Version needed to extract" is higher than "Version made by" …
=> chore: release v4.0.0

src/spec.rs, src/types.rs, src/write.rs
Per section 4.3.9.4 of `APPNOTE`, writers should include the magic signature for data descriptors. Despite it being optional, some parsers require it, so this should help increase compatibility.
This commit also switches from performing raw writes for data descriptors to using the `FixedSizeBlock` API.
---
```
4.3.9.4 When writing ZIP files, implementors SHOULD include the
signature value marking the data descriptor record.  When
the signature is used, the fields currently defined for
the data descriptor record will immediately follow the
signature.
```
=> fix: Include magic signature when writing data descriptors

src/write.rs
This way, it's possible to retrieve the original writer after writing a file via `ZipWriter::new_stream()`.
=> feat: Add StreamWriter::into_inner()

.github/workflows/ci.yaml, Cargo.toml, README.md, examples/write-large-file.rs
Upgrade to bzip2 0.6.0, which has the benefit of being in pure Rust now.
=> deps: Upgrade to bzip2 0.6.0

src/types.rs
=> chore: Move deprecated annotations to fix a Clippy warning

CHANGELOG.md, Cargo.toml
* `zip`: 4.4.0 -> 4.5.0 (✓ API compatible changes)
<blockquote>
- Allow reading ZIP files where the central directory comes *before* the files ([#384](https://github.com/zip-rs/zip2/pull/384)) ([#396](https://github.com/zip-rs/zip2/pull/396))
</blockquote>
</p></details>
---
=> chore: release v4.5.0

src/write.rs
Make ppmd/xz compression work if only the respective feature is enabled.
=> fix: enable clamp_opt for ppmd and xz

CHANGELOG.md, Cargo.toml
* `zip`: 4.6.0 -> 4.6.1 (✓ API compatible changes)
<blockquote>
- Swap to liblzma from lzma-rs introduced issue ([#407](https://github.com/zip-rs/zip2/pull/407))
</blockquote>
</p></details>
---
=> chore: release v4.6.1

CHANGELOG.md, Cargo.toml
* `zip`: 4.6.1 -> 5.0.0 (⚠ API breaking changes)
```text
--- failure feature_not_enabled_by_default: package feature is not enabled by default ---
Description:
A feature is no longer enabled by default for this package. This will break downstream crates which rely on the package's default features and require the functionality of this feature.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#cargo-feature-remove-another
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.43.0/src/lints/feature_not_enabled_by_default.ron
Failed in:
feature lzma-static in the package's Cargo.toml
```
<blockquote>
- Implement by_path*() methods on ZipArchive ([#382](https://github.com/zip-rs/zip2/pull/382))
</blockquote> …
=> chore: release v5.0.0

CHANGELOG.md, Cargo.toml
* `zip`: 5.0.1 -> 5.1.0 (✓ API compatible changes)
<blockquote>
- Add legacy shrink/reduce/implode compression ([#303](https://github.com/zip-rs/zip2/pull/303))
</blockquote>
</p></details>
---
=> chore: release v5.1.0
